'use strict';

// Regenerates PodStack's ship data from EVE's static data export (SDE):
//
//   resources/ships.js   every published ship on the market: class, race, tech/meta group and the skills it needs
//
// Usage: `npm run update-ships` downloads the latest SDE from CCP (about 100 MB), or
// `npm run update-ships -- <folder>` uses an already extracted JSONL SDE. It prints which ships are new or removed.
// Run it after CCP adds ships (alongside update-skills), then review and commit the changes.

const fs = require('fs');
const os = require('os');
const path = require('path');
const {execFileSync} = require('child_process');

const ROOT = path.join(__dirname, '..');
const SDE_URL = 'https://developers.eveonline.com/static-data/tranquility';
const SHIP_CATEGORY = 6;
const FILES = ['types.jsonl', 'groups.jsonl', 'typeDogma.jsonl', 'races.jsonl', 'metaGroups.jsonl'];

// the same skill/level dogma attribute pairs skills use for their prerequisites
const PREREQUISITES = [[182, 277], [183, 278], [184, 279], [1285, 1286], [1289, 1287], [1290, 1288]];

async function downloadSde() {
    const latest = await (await fetch(`${SDE_URL}/latest.jsonl`)).json();
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), `sde-${latest.buildNumber}-`));
    const zip = path.join(dir, 'sde.zip');

    console.log(`Downloading SDE build ${latest.buildNumber} (${latest.releaseDate.slice(0, 10)})…`);
    const res = await fetch(`${SDE_URL}/eve-online-static-data-${latest.buildNumber}-jsonl.zip`);
    if (!res.ok) {
        throw new Error(`SDE download failed (${res.status})`);
    }
    fs.writeFileSync(zip, Buffer.from(await res.arrayBuffer()));

    // unzip on Linux/macOS; Windows 10+ ships a tar that reads zip files
    try {
        execFileSync('unzip', ['-o', '-q', zip, ...FILES, '-d', dir]);
    } catch {
        execFileSync('tar', ['-xf', zip, '-C', dir, ...FILES]);
    }
    return {dir, build: latest.buildNumber, date: latest.releaseDate.slice(0, 10)};
}

function readJsonl(dir, file) {
    return fs.readFileSync(path.join(dir, file), 'utf8').split('\n').filter(Boolean).map(line => JSON.parse(line));
}

function loadCurrent() {
    try {
        const source = fs.readFileSync(path.join(ROOT, 'resources', 'ships.js'), 'utf8')
            .replace(/^'use strict';/, '').replace(/export default/, 'module.exports =');
        const mod = {exports: {}};
        new Function('module', 'exports', source)(mod, mod.exports);
        return mod.exports;
    } catch {
        return {ships: {}};
    }
}

function build(dir) {
    const groups = new Map(readJsonl(dir, 'groups.jsonl').map(g => [g._key, g]));
    const races = new Map(readJsonl(dir, 'races.jsonl').map(r => [r._key, r.name.en]));
    const metaGroups = new Map(readJsonl(dir, 'metaGroups.jsonl').map(m => [m._key, m.name.en]));
    const dogma = new Map(readJsonl(dir, 'typeDogma.jsonl')
        .map(t => [t._key, new Map((t.dogmaAttributes || []).map(a => [a.attributeID, a.value]))]));

    const ships = {};
    const usedRaces = {};
    for (const type of readJsonl(dir, 'types.jsonl')) {
        const group = groups.get(type.groupID);
        // published and sold on the market: leaves out NPC hulls, tournament prizes and the like
        if (!group || group.categoryID !== SHIP_CATEGORY || !type.published || type.marketGroupID === undefined) {
            continue;
        }

        const attributes = dogma.get(type._key) || new Map();
        const skills = PREREQUISITES
            .filter(([skill]) => attributes.has(skill))
            .map(([skill, level]) => ({id: attributes.get(skill), level: attributes.get(level) || 1}));

        if (type.raceID !== undefined && races.has(type.raceID)) {
            usedRaces[type.raceID] = races.get(type.raceID);
        }
        ships[type._key] = {
            type_id: type._key,
            name: type.name.en,
            group_id: type.groupID,
            group: group.name.en,
            race_id: type.raceID,
            meta: metaGroups.get(type.metaGroupID) || 'Tech I',
            skills,
        };
    }

    return {ships, races: usedRaces};
}

function header(build, date) {
    return `'use strict';\n\n// Every published ship on the market, from EVE's static data export, build ${build} (${date}), generated by scripts/update-ships.js.\n`;
}

(async () => {
    const folder = process.argv[2];
    let source;
    if (folder !== undefined) {
        // the build is in _sde.jsonl when the folder has it
        let info = {};
        try {
            info = readJsonl(folder, '_sde.jsonl')[0] || {};
        } catch {
            // no _sde.jsonl: the build shows as "local"
        }
        source = {dir: folder, build: info.buildNumber || 'local', date: (info.releaseDate || new Date().toISOString()).slice(0, 10)};
    } else {
        source = await downloadSde();
    }

    const current = loadCurrent();
    const data = build(source.dir);

    const added = Object.keys(data.ships).filter(id => current.ships[id] === undefined);
    const removed = Object.keys(current.ships).filter(id => data.ships[id] === undefined);
    console.log(`${Object.keys(data.ships).length} ships (${added.length} new, ${removed.length} removed)`);
    added.slice(0, 50).forEach(id => console.log(`  + ${data.ships[id].name}`));
    removed.slice(0, 50).forEach(id => console.log(`  - ${current.ships[id].name}`));

    fs.writeFileSync(path.join(ROOT, 'resources', 'ships.js'),
        header(source.build, source.date) + 'export default ' + JSON.stringify(data, null, 1) + ';\n');
})().catch(err => {
    console.error(err);
    process.exit(1);
});
