'use strict';

// Oodle1 decompressor: the older of RAD's compressors for Granny 2 sections, used by most of EVE's ship models (the
// newer ones use BitKnit 2, see BitKnit.js). An adaptive arithmetic coder over LZ literals and back-references, decoded
// with three successive dictionaries whose parameters lead the stream.
//
// A JavaScript port of gr2_decompress.cpp from nwn2mdk (https://github.com/Arbos/nwn2mdk), itself derived from
// xoreos-tools' Granny decoder by berenm (https://github.com/berenm/xoreos-tools). That code is distributed under the
// Boost Software License 1.0, reproduced here as it requires:
//
//   Boost Software License - Version 1.0 - August 17th, 2003
//
//   Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
//   accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute,
//   execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to
//   whom the Software is furnished to do so, all subject to the following:
//
//   The copyright notices in the Software and this entire statement, including the above license grant, this
//   restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and
//   all derivative works of the Software, unless such copies or derivative works are solely in the form of
//   machine-executable object code generated by a source language processor.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//   WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
//   COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
//   CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//   THE SOFTWARE.

const RANGE = 0x4000;
const LONG_COPIES = [128, 192, 256, 512];

// the arithmetic decoder: reads the stream 7 bits at a time, offset by one bit
class Decoder {
    constructor(src, pos) {
        this.src = src;
        this.pos = pos;
        this.numer = src[pos] >>> 1;
        this.denom = 0x80;
        this.nextDenom = 0;
    }

    byte(i) {
        const b = this.src[i];
        return b === undefined ? 0 : b;   // the stream may be read slightly past its end, as zeroes
    }

    decode(max) {
        while (this.denom <= 0x800000) {
            this.numer = ((this.numer << 8) | ((this.byte(this.pos) << 7) & 0x80) | ((this.byte(this.pos + 1) >>> 1) & 0x7f)) >>> 0;
            this.pos++;
            this.denom = (this.denom * 256) >>> 0;
        }
        this.nextDenom = Math.floor(this.denom / max);
        return Math.min(Math.floor(this.numer / this.nextDenom), max - 1);
    }

    commit(max, value, err) {
        this.numer = (this.numer - this.nextDenom * value) >>> 0;
        if (value + err < max) {
            this.denom = (this.nextDenom * err) >>> 0;
        } else {
            this.denom = (this.denom - this.nextDenom * value) >>> 0;
        }
        return value;
    }

    decodeAndCommit(max) {
        return this.commit(max, this.decode(max), 1);
    }
}

// An adaptive set of the values seen so far, with weights; slot 0 is the escape for a value not seen yet.
class WeighWindow {
    constructor(maxValue, countCap) {
        this.weightTotal = 4;
        this.countCap = (countCap + 1) & 0xffff;
        this.ranges = [0, RANGE];
        this.weights = [4];
        this.values = [0];
        this.threshIncrease = 4;
        this.threshRangeRebuild = 8;
        this.threshWeightRebuild = Math.max(256, Math.min(32 * maxValue, 15160));
        this.threshIncreaseCap = maxValue > 64 ? Math.min(2 * maxValue, Math.floor(this.threshWeightRebuild / 2) - 32) : 128;
    }

    rebuildRanges() {
        const rangeWeight = Math.floor(8 * RANGE / this.weightTotal);
        let start = 0;
        this.ranges = new Array(this.weights.length + 1);
        for (let i = 0; i < this.weights.length; i++) {
            this.ranges[i] = start;
            start += Math.floor(this.weights[i] * rangeWeight / 8);
        }
        this.ranges[this.weights.length] = RANGE;

        if (this.threshIncrease > Math.floor(this.threshIncreaseCap / 2)) {
            this.threshRangeRebuild = (this.weightTotal + this.threshIncreaseCap) & 0xffff;
        } else {
            this.threshIncrease = (this.threshIncrease * 2) & 0xffff;
            this.threshRangeRebuild = (this.weightTotal + this.threshIncrease) & 0xffff;
        }
    }

    rebuildWeights() {
        const w = this.weights;
        const v = this.values;
        for (let i = 0; i < w.length; i++) {
            w[i] = w[i] >> 1;
        }
        this.weightTotal = w.reduce((sum, x) => sum + x, 0) & 0xffff;

        const swap = (a, b) => {
            [w[a], w[b]] = [w[b], w[a]];
            [v[a], v[b]] = [v[b], v[a]];
        };
        // drop the values whose weight fell to zero (except the escape)
        for (let i = 1; i < w.length; i++) {
            while (i < w.length && w[i] === 0) {
                swap(i, w.length - 1);
                w.pop();
                v.pop();
            }
        }
        // the heaviest value goes last
        let max = -1;
        for (let i = 1; i < w.length; i++) {
            if (max === -1 || w[i] > w[max]) {
                max = i;
            }
        }
        if (max !== -1) {
            swap(max, w.length - 1);
        }

        if (w.length < this.countCap && w[0] === 0) {
            w[0] = 1;
            this.weightTotal = (this.weightTotal + 1) & 0xffff;
        }
    }

    // {value} for a value seen before, or {slot} for a new one, whose value the caller decodes and stores
    tryDecode(dec) {
        if (this.weightTotal >= this.threshRangeRebuild) {
            if (this.threshRangeRebuild >= this.threshWeightRebuild) {
                this.rebuildWeights();
            }
            this.rebuildRanges();
        }

        const value = dec.decode(RANGE);
        // the last range starting at or below value
        let lo = 0;
        let hi = this.ranges.length - 1;
        while (lo < hi) {
            const mid = (lo + hi + 1) >> 1;
            if (this.ranges[mid] <= value) {
                lo = mid;
            } else {
                hi = mid - 1;
            }
        }
        const index = lo;
        dec.commit(RANGE, this.ranges[index], this.ranges[index + 1] - this.ranges[index]);

        this.weights[index] = (this.weights[index] + 1) & 0xffff;
        this.weightTotal = (this.weightTotal + 1) & 0xffff;

        if (index > 0) {
            return {value: this.values[index]};
        }

        if (this.weights.length >= this.ranges.length && dec.decodeAndCommit(2) === 1) {
            const i = this.ranges.length + dec.decodeAndCommit(this.weights.length - this.ranges.length + 1) - 1;
            this.weights[i] = (this.weights[i] + 2) & 0xffff;
            this.weightTotal = (this.weightTotal + 2) & 0xffff;
            return {value: this.values[i]};
        }

        this.values.push(0);
        this.weights.push(2);
        this.weightTotal = (this.weightTotal + 2) & 0xffff;
        if (this.weights.length === this.countCap) {
            this.weightTotal = (this.weightTotal - this.weights[0]) & 0xffff;
            this.weights[0] = 0;
        }
        return {slot: this.values.length - 1};
    }

    // a value from the window, decoding a new one with decodeAndCommit(max) when it's one not seen before
    next(dec, max) {
        const r = this.tryDecode(dec);
        if (r.slot === undefined) {
            return r.value;
        }
        const value = dec.decodeAndCommit(max) & 0xffff;
        this.values[r.slot] = value;
        return value;
    }
}

class Dictionary {
    constructor(params) {
        this.decodedSize = 0;
        this.backrefSize = 0;

        this.decodedValueMax = params.decodedValueMax;
        this.backrefValueMax = params.backrefValueMax;
        this.lowbitValueMax = Math.min(this.backrefValueMax + 1, 4);
        this.midbitValueMax = Math.min(Math.floor(this.backrefValueMax / 4) + 1, 256);
        this.highbitValueMax = Math.floor(this.backrefValueMax / 1024) + 1;

        this.lowbitWindow = new WeighWindow(this.lowbitValueMax - 1, this.lowbitValueMax);
        this.highbitWindow = new WeighWindow(this.highbitValueMax - 1, params.highbitCount + 1);
        this.midbitWindows = Array.from({length: this.highbitValueMax}, () => new WeighWindow(this.midbitValueMax - 1, this.midbitValueMax));
        this.decodedWindows = Array.from({length: 4}, () => new WeighWindow(this.decodedValueMax - 1, params.decodedCount));
        this.sizeWindows = [];
        for (let i = 0; i < 4; i++) {
            for (let j = 0; j < 16; j++) {
                this.sizeWindows.push(new WeighWindow(64, params.sizesCount[3 - i]));
            }
        }
        this.sizeWindows.push(new WeighWindow(64, params.sizesCount[0]));
    }

    // decodes one literal or back-reference at dst[pos]; returns how many bytes it produced
    block(dec, dst, pos) {
        this.backrefSize = this.sizeWindows[this.backrefSize].next(dec, 65);

        if (this.backrefSize > 0) {
            const size = this.backrefSize < 61 ? this.backrefSize + 1 : LONG_COPIES[this.backrefSize - 61];
            const range = Math.min(this.backrefValueMax, this.decodedSize);

            const low = this.lowbitWindow.next(dec, this.lowbitValueMax);
            const high = this.highbitWindow.next(dec, Math.floor(range / 1024) + 1);
            const mid = this.midbitWindows[high].next(dec, Math.min(Math.floor(range / 4) + 1, 256));
            const offset = (high << 10) + (mid << 2) + low + 1;

            this.decodedSize += size;
            if (offset > pos) {
                throw new Error(`Oodle1: back-reference before the start at ${pos}`);
            }
            const end = Math.min(pos + size, dst.length);
            for (let i = pos; i < end; i++) {
                dst[i] = dst[i - offset];
            }
            return size;
        }

        dst[pos] = this.decodedWindows[pos % 4].next(dec, this.decodedValueMax) & 0xff;
        this.decodedSize++;
        return 1;
    }
}

// the three dictionaries' parameters (12 bytes each, packed bit fields)
function readParameters(src) {
    const view = new DataView(src.buffer, src.byteOffset, src.byteLength);
    return [0, 1, 2].map(i => {
        const a = view.getUint32(i * 12, true);
        const b = view.getUint32(i * 12 + 4, true);
        return {
            decodedValueMax: a & 0x1ff,
            backrefValueMax: a >>> 9,
            decodedCount: b & 0x1ff,
            highbitCount: b >>> 19,
            sizesCount: [src[i * 12 + 8], src[i * 12 + 9], src[i * 12 + 10], src[i * 12 + 11]],
        };
    });
}

/**
 * Decompresses an Oodle1 Granny section.
 *
 * @param {Uint8Array} src the compressed section
 * @param {number} size the decompressed size
 * @param {number} stop0 where the first dictionary's data ends (the section header's first 16-bit offset)
 * @param {number} stop1 where the second's ends (its first 8-bit offset)
 * @returns {Uint8Array}
 */
export function decompress(src, size, stop0, stop1) {
    const dst = new Uint8Array(size);
    if (src.length === 0) {
        return dst;
    }
    const params = readParameters(src);
    const dec = new Decoder(src, 36);
    const stops = [stop0, stop1, size];
    let pos = 0;
    for (let i = 0; i < 3; i++) {
        const dictionary = new Dictionary(params[i]);
        while (pos < Math.min(stops[i], size)) {
            pos += dictionary.block(dec, dst, pos);
        }
    }
    return dst;
}
